DROP TABLE IF EXISTS app.admin_broadcasts;
DROP TABLE IF EXISTS app.notification_deliveries;
DROP TABLE IF EXISTS app.notification_preferences;
DROP INDEX IF EXISTS app.notifications_recipient_dedupe_idx;
DROP INDEX IF EXISTS app.notifications_org_unread_idx;
DROP INDEX IF EXISTS app.notifications_user_unread_idx;
DROP INDEX IF EXISTS app.notifications_admin_unread_idx;
ALTER TABLE app.notifications ADD COLUMN recipient_id UUID;
ALTER TABLE app.notifications ADD COLUMN audience TEXT;
UPDATE app.notifications SET recipient_id = COALESCE(recipient_user_id, recipient_admin_id), audience = CASE WHEN recipient_admin_id IS NULL THEN 'customer' ELSE 'admin' END;
ALTER TABLE app.notifications DROP CONSTRAINT IF EXISTS notifications_recipient_check;
ALTER TABLE app.notifications DROP COLUMN recipient_org_id;
ALTER TABLE app.notifications DROP COLUMN recipient_user_id;
ALTER TABLE app.notifications DROP COLUMN recipient_admin_id;
ALTER TABLE app.notifications DROP COLUMN event_type;
ALTER TABLE app.notifications DROP COLUMN reference_id;
ALTER TABLE app.notifications DROP COLUMN dedupe_key;
ALTER TABLE app.notifications DROP COLUMN severity;
ALTER TABLE app.notifications DROP COLUMN source;
ALTER TABLE app.notifications DROP COLUMN created_by_admin_id;
ALTER TABLE app.notifications RENAME COLUMN body TO description;
ALTER TABLE app.notifications RENAME COLUMN icon TO emoji;
ALTER TABLE app.notifications RENAME COLUMN link_url TO link;
ALTER TABLE app.notifications RENAME TO dashboard_notifications;
ALTER TABLE app.dashboard_notifications ADD CONSTRAINT dashboard_notifications_audience_check CHECK (audience IN ('customer', 'admin'));
